[package]
name = "rust-port-sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zzz = "0.1.0"
loading = "0.1.2"